 version: 2.1
 jobs:
    install:
      docker:
        - image: circleci/node:dubnium-browsers
      working_directory: ~/repo
      steps:
        - checkout
        - restore_cache:
            keys:
              - {{ .Environment.CACHE_VERSION }}-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
              - {{ .Environment.CACHE_VERSION }}-dependencies-
        - run: yarn global add node-gyp && yarn install
        - save_cache:
          paths:
            - node_modules
          key: {{ .Environment.CACHE_VERSION }}-dependencies-{{ checksum "package.json" }}
